### PR TITLE
Allow zero count for buildMany

### PR DESCRIPTION
**Pull request by ncjones**

### CODE REVIEW

**Comment by ratson** [comment]
@ncjones What is the use case? I am not sure if it is worth a breaking change.

**Comment by ncjones** [comment]
Let's say you have a cucumber step definition which takes a parameter for the number of entities:

```gherkin
Given a widget with 2 dongles
```

Then currently we need special handling for the "0" case.

I do not consider this to be a breaking change; I doubt any code has been written which will fail when buildMany stops throwing an error in this scenario.

**Comment by ratson** [comment]
This change does break the test suite, and it could be a behavior some tests rely on.
Essentially, `buildMany` with zero is an empty array, which is not safe for user to loop through it for assertions, because it silently skips the checks.

I think adding `buildMany0` or something similar would help if that is a common pattern. Keeping zero count as special case seems better.

**Comment by ncjones** [comment]
I guess we will have to agree to disagree. `buildMany0` is 100% useless as it's the same as `[]`.

**Comment by ratson** [comment]
> I guess we will have to agree to disagree. `buildMany0` is 100% useless as it's the same as `[]`.

@ncjones I mean `buildMany0` with your suggested semantic (maybe a better name), which is more explicit for the empty array case, so people know there is an edge case when looping function on it.

Changing existing semantic will likely have to change `AssocAttrsMany` too,
https://github.com/ratson/factory-bot/search?q=%22if+%28typeof+num+%21%3D%3D+%27number%27+%7C%7C+num+%3C+1%29+%7B%22

**Pull request closed without merging**
